### ISSUE TITLE
Update to version 18877 of the jar

### ISSUE THREAD

**Issue by thibaultmol** [flathub/org.openstreetmap.josm#89]

**Comment by bmillemathias** [comment]
Hello, What is the issue about ?

**Comment by thibaultmol** [comment]
Sorry, seems like I submitted the wrong tab (had filled out a proper issues in another tab)
![image](https://github.com/flathub/org.openstreetmap.josm/assets/1010226/5b6320e8-e6b9-4562-9566-43ab075b1ee7)

There's a new version of josm jar out ^

**Comment by bmillemathias** [comment]
version 18877 is development release, we don´t package such versions (this is the commit number, so there is a version per commit). the latest stable version is given on page https://josm.openstreetmap.de/wiki/Download.

The issue is rather on the plugin side which depends on development version.

Sorry we cannot help here, until a new stable version of JOSM is release.

Best

**Comment by bmillemathias** [comment]
another solution is to ask JOSM developers to release a new stable version to fill the dependency issue. Perhaps you can do that.

**Comment by thibaultmol** [comment]
Ah sorry, I assumed that it was a new stable version. 
(Because the plugin shouldn't require a non-stable version of the program......)
I hadn't actually checked the website yet
👍

**Comment by bmillemathias** [comment]
> (Because the plugin shouldn't require a non-stable version of the program......)

yes this is a common issue with the JOSM plugins, as there is no dev/stable separate branches / releases.

**Comment by thibaultmol** [comment]
Isn't there "newest tested version" and "latest" ? Isn't that basically stable/dev?
